### ISSUE TITLE
RHEL8-cis fails on UEFI

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/kickstart#1]
with `EFI System Partition cannot be of type lvmpv`. Worked after adding
`part /boot/efi --fstype vfat --size=600 --ondisk=vda` after `part /boot --fstype="xfs" --ondisk=vda --size=1024`.

We should test this and adjust all configs if required.

**Comment by markuslf** [comment]
Be aware of your different `ondisk` statements: 1x "vda", 1x "sda".

**Comment by NavidSassan** [comment]
copy-paste error, adjusted the comment
