### ISSUE TITLE
Disk "vda" given in ignoredisk command does not exist.   

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/kickstart#2]
If running the current Kickstart file on a VM having one IDE disk, I get the error `Disk "vda" given in ignoredisk command does not exist`.

![image](https://github.com/Linuxfabrik/kickstart/assets/31855393/7b91dbbf-86d1-4051-8147-9234ef9dfb5e)

**Comment by Geertsky** [comment]
parameter `lfdisk=` defaults to `vda` for other disks set the kernel parameter correspondingly [lfdisk=\<disk\>](https://github.com/Linuxfabrik/kickstart#additional-usefull-kernel-cmdline-arguments)

**Comment by markuslf** [comment]
No chance to get the correct name ``vda`` vs. ``sda`` automatically?

**Comment by Geertsky** [comment]
There can be multiple devices... vda,vdb,sda,nvme0. which one to pick

**Comment by markuslf** [comment]
Ok, leave it at that.
